[supervisord]
nodaemon=true
logfile=/dev/null
pidfile=/tmp/supervisord.pid
user=root

[program:email-queue]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/backend/artisan queue:work --queue=emails-priority,emails,default --sleep=1 --tries=5 --timeout=120 --verbose
directory=/var/www/backend
autostart=true
autorestart=true
startsecs=2
stopwaitsecs=130
numprocs=4
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:email-scheduler]
command=php /var/www/backend/artisan schedule:work
directory=/var/www/backend
autostart=true
autorestart=true
startsecs=2
stopwaitsecs=30
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
